#!/bin/bash
# deep-research Lab warm worker. Runs as one Slurm job and executes Lab tasks
# (smoke tests, planner probes, short full runs) handed to it through a spool folder, so
# a burst of Lab work shares one warm node instead of booting one node per job.
#
#   <WARM>/queue/<task>/      a task: run.sh (+ need_sec, exclusive), claimed by rename
#   <WARM>/running/<task>/    being run; a file named `cancel` stops it
#   <WARM>/done/<task>/       finished: rc, log, started, finished, node
#   <WARM>/workers/<job>.json heartbeat per worker (node, busy, draining, updated)
#
# Up to MAX_PAR tasks run at once, each in its own session with a private TMPDIR; a task
# marked `exclusive` (a full run that uses every core) runs alone. A
# task is only claimed if it can finish (need_sec) before this job's time limit
# (END_TS); otherwise the worker marks itself draining so the dashboard starts another.
# The worker exits after IDLE_MIN minutes with nothing to do (IDLE_SEC overrides, for
# tests), on a `stop` file, or on SIGUSR1/SIGTERM (Slurm sends USR1 60 s before the limit).
# Generated by deep-research; re-uploaded on every start, do not edit on the cluster.
set -u
WARM=${WARM:?}
IDLE_SEC=${IDLE_SEC:-$(( ${IDLE_MIN:-20} * 60 ))}
MAX_PAR=${MAX_PAR:-2}
END_TS=${END_TS:-$(( $(date +%s) + ${WARM_LIMIT_SEC:-86400} ))}
POLL=${POLL:-2}
mkdir -p "$WARM/queue" "$WARM/running" "$WARM/done" "$WARM/workers"
cd "$WARM" || exit 1
node=$(hostname -s)
job=${SLURM_JOB_ID:-local$$}
last_work=$(date +%s)
last_clean=0
draining=false
BASE_TMP=${TMPDIR:-/tmp}
declare -A PIDS=()
EXCL=""

beat() {
  local busy
  busy=$(printf '%s ' "${!PIDS[@]}")
  printf '{"job": "%s", "node": "%s", "cpus": "%s", "busy": "%s", "draining": %s, "updated": %s, "end": %s}\n' \
    "$job" "$node" "${SLURM_CPUS_ON_NODE:-}" "${busy% }" "$draining" "$(date +%s)" "$END_TS" \
    > "workers/.$job.tmp" && mv -f "workers/.$job.tmp" "workers/$job.json"
}

finish() {  # task rc
  local t=$1 rc=$2
  echo "$rc" > "running/$t/rc"
  date +%s > "running/$t/finished"
  rm -rf "done/$t"
  mv "running/$t" "done/$t"
  unset "PIDS[$t]"
  [ "$EXCL" = "$t" ] && EXCL=""
  echo "[warm] $(date -u +%T) task $t finished rc=$rc"
}

stop_all() {
  for t in "${!PIDS[@]}"; do kill -TERM -- "-${PIDS[$t]}" 2>/dev/null; done
  sleep 2
  for t in "${!PIDS[@]}"; do
    kill -KILL -- "-${PIDS[$t]}" 2>/dev/null
    finish "$t" 143
  done
  rm -f "workers/$job.json"
  echo "[warm] $(date -u +%T) worker stopped"
}
trap 'stop_all; exit 0' TERM INT USR1

echo "[warm] job $job on $node, ${SLURM_CPUS_ON_NODE:-?} CPUs, idle limit ${IDLE_SEC}s, up to $MAX_PAR tasks"
while true; do
  now=$(date +%s)
  # reap finished tasks and honour cancels
  for t in "${!PIDS[@]}"; do
    pid=${PIDS[$t]}
    if [ -e "running/$t/cancel" ]; then
      kill -TERM -- "-$pid" 2>/dev/null; sleep 1; kill -KILL -- "-$pid" 2>/dev/null
    fi
    if ! kill -0 "$pid" 2>/dev/null; then
      wait "$pid"; rc=$?
      [ -e "running/$t/cancel" ] && rc=130
      finish "$t" "$rc"
      last_work=$now
    fi
  done
  # claim new tasks, oldest first, if they fit before the time limit
  if [ "${#PIDS[@]}" -lt "$MAX_PAR" ] && [ "$draining" = false ] && [ -z "$EXCL" ]; then
    for q in $(ls -1tr queue 2>/dev/null); do
      [ "${#PIDS[@]}" -ge "$MAX_PAR" ] && break
      [ -n "$EXCL" ] && break
      [ -f "queue/$q/run.sh" ] || continue
      # an exclusive task waits until the node is free
      if [ -e "queue/$q/exclusive" ] && [ "${#PIDS[@]}" -gt 0 ]; then continue; fi
      need=$(cat "queue/$q/need_sec" 2>/dev/null || echo 600)
      if [ $(( now + need + 90 )) -gt "$END_TS" ]; then
        draining=true   # leave it for a fresh worker
        echo "[warm] $(date -u +%T) task $q needs ${need}s, more than this worker has left: draining"
        break
      fi
      if mv "queue/$q" "running/$q" 2>/dev/null; then
        date +%s > "running/$q/started"
        echo "$node" > "running/$q/node"
        echo "[warm] $(date -u +%T) task $q started"
        mkdir -p "$BASE_TMP/lab-$q"
        ( cd "running/$q" && TMPDIR="$BASE_TMP/lab-$q" exec setsid bash ./run.sh > log 2>&1 ) &
        PIDS[$q]=$!
        [ -e "running/$q/exclusive" ] && EXCL=$q
        last_work=$now
      fi
    done
  fi
  beat
  if [ "${#PIDS[@]}" -eq 0 ]; then
    if [ "$draining" = true ] || [ $(( now - last_work )) -ge "$IDLE_SEC" ]; then
      echo "[warm] $(date -u +%T) $([ "$draining" = true ] && echo draining done || echo "idle for ${IDLE_SEC}s"), exiting"
      rm -f "workers/$job.json"
      exit 0
    fi
  fi
  if [ -e stop ]; then rm -f stop; stop_all; exit 0; fi
  # finished tasks older than a day go
  if [ $(( now - last_clean )) -ge 600 ]; then
    find done -mindepth 1 -maxdepth 1 -mmin +1440 -exec rm -rf {} + 2>/dev/null
    find workers -name '*.json' -mmin +10 -delete 2>/dev/null   # heartbeats of dead workers
    last_clean=$now
  fi
  sleep "$POLL"
done
